/**
 * hnpwa
 * use this to generate from swagger tools
 *
 * OpenAPI spec version: 0
 * Contact: jim@vsiwest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.hnpwa.models


/**
 *
 * @param id
 * @param title
 * @param points
 * @param user
 * @param time
 * @param time_ago
 * @param comments_count
 * @param type
 * @param url
 * @param domain
 */
data class FeedItem(
        val id: Int? = null,
        val title: String? = null,
        val points: Int? = null,
        val user: String? = null,
        val time: Int? = null,
        val time_ago: String? = null,
        val comments_count: Int? = null,
        val type: String? = null,
        val url: String? = null,
        val domain: String? = null
) {

}

