/**
* hnpwa
* use this to generate from swagger tools
*
* OpenAPI spec version: 0
* Contact: jim@vsiwest.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.hnpwa.models

/**
 * 
 * @param id 
 * @param title 
 * @param points 
 * @param user 
 * @param time 
 * @param time_ago 
 * @param type 
 * @param content 
 * @param comments 
 * @param comments_count 
 * @param url 
 * @param domain 
 */
data class Item (
    val id: kotlin.Int,
    val title: kotlin.String,
    val user: kotlin.String,
    val time: kotlin.Int,
    val time_ago: kotlin.String,
    val url: kotlin.String,
    val points: kotlin.Int? = null,
    val type: kotlin.String? = null,
    val content: kotlin.String? = null,
    val comments: kotlin.Array<Item>? = null,
    val comments_count: kotlin.Int? = null,
    val domain: kotlin.String? = null
) {

}

