/**
* hnpwa
* use this to generate from swagger tools
*
* OpenAPI spec version: 0
* Contact: jim@vsiwest.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.hnpwa.models


/**
 * 
 * @param created_time 
 * @param created 
 * @param id 
 * @param karma 
 */
data class User (
    val created_time: kotlin.Int,
    val created: kotlin.String,
    val id: kotlin.String,
    val karma: kotlin.Int
) {

}

