/**
* hnpwa
* use this to generate from swagger tools
*
* OpenAPI spec version: 0
* Contact: jim@vsiwest.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.hnpwa

import io.ktor.application.ApplicationCall
import io.ktor.http.HttpMethod
import io.ktor.locations.*
import io.ktor.pipeline.PipelineContext
import io.ktor.routing.Route
import io.ktor.routing.method


// NOTE: ktor-location@0.9.0 is missing extension for Route.delete. This includes it.
inline fun <reified T : Any> Route.delete(noinline body: suspend PipelineContext<Unit, ApplicationCall>.(T) -> Unit): Route {
    return location(T::class) {
        method(HttpMethod.Delete) {
            handle(body)
        }
    }
}

object Paths {
    /**
     * 
     * 
     * @param page  
     */
    @Location("/ask/{page}.json") class askPageJsonGet(val page: kotlin.Int)

    /**
     * 
     * 
     * @param id  
     */
    @Location("/item/{id}.json") class itemIdJsonGet(val id: kotlin.Int)

    /**
     * 
     * 
     * @param page  
     */
    @Location("/newest/{page}.json") class newestPageJsonGet(val page: kotlin.Int)

    /**
     * 
     * 
     * @param page  
     */
    @Location("/news/{page}.json") class newsPageJsonGet(val page: kotlin.Int)

    /**
     * 
     * 
     * @param page  
     */
    @Location("/show/{page}.json") class showPageJsonGet(val page: kotlin.Int)

    /**
     * 
     * 
     * @param id  
     */
    @Location("/user/{id}.json") class userIdJsonGet(val id: kotlin.String)

}
